# @author Simon de Hartog <simon@fs2a.pro>
# @copyright Fs2a Ltd. (c) 2018
# vim:set ts=2 sw=2 expandtab:
---
version: "3"
services:
  bld:
    build: bld
    command: sleep infinity
    hostname: bld
    image: "fs2a/bld"
    volumes:
      - "/usr/portage:/usr/portage:ro"
      - "binpkgs:/opt/binpkgs"

volumes:
  binpkgs:
