# @author Simon de Hartog <simon@fs2a.pro>
# @copyright Fs2a Ltd. (c) 2018
# vim:set ts=2 sw=2 expandtab:
---
version: "3"
services:

  base:
    build: base
    command: sleep infinity
    hostname: base
    image: "fs2a/base"
    volumes:
      - "binpkgs:/opt/binpkgs:ro"
      - "/usr/portage:/usr/portage:ro"

  bld:
    build: bld
    command: sleep infinity
    hostname: bld
    image: "fs2a/bld"
    volumes:
      - "binpkgs:/opt/binpkgs"
      - "/usr/portage:/usr/portage:ro"
      - "/zfs/distfiles:/zfs/distfiles"

volumes:
  binpkgs:
